In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
path = '/content/drive/My Drive/NNFL/data4.xlsx'
data = pd.read_excel(path, header = None)
data = np.array(data)
np.random.shuffle(data)

In [ ]:
def normalise(x):
  xmean = np.mean(x, axis=1).reshape(x.shape[0], 1)
  xstd = np.std(x, axis=1).reshape(x.shape[0], 1)
  z = (x-xmean)/xstd
  return z

In [ ]:
N, M = data.shape

ones = np.ones((N, 1), dtype='float32')

X = data[:, :M-1]
X = np.concatenate([ones, X], axis=1)
Y = data[:, M-1:]

N, M = data.shape

In [ ]:
X = normalise(X)

In [ ]:
tr_ratio = 0.6
num_tr = int (N * tr_ratio)
x_train = X[:num_tr, :]
x_test = X[num_tr:, :]
y_train = Y[:num_tr, :]
y_test = Y[num_tr:, :]

In [ ]:
def model(w, x, y, iterations, alpha):
  delta = 0.01
  costs = []
  grads = []

  for iter in range(iterations):
    
    pred = np.dot(w, x.T)
    pred = sigmoid(pred)

    dp = x_train.shape[0]

    costval = (-1.0 / dp) * (np.sum(np.multiply(y, np.log(pred+delta)) + np.multiply(1.0-y, np.log(1.0 - pred+delta)), axis=1))
    costs.append(costval)

    gradval = np.dot((pred - y), x)
    grads.append(gradval)

    w = w - alpha*gradval
    
  return costs, grads, w

In [ ]:
def sigmoid(z):
  return 1.0 / (1 + np.exp(-z))

In [ ]:
# model 1
# 1 is positive, 2 and 3 are negative

alpha = 0.1
iterations = 6000
w = np.random.randn(1, x_train.shape[1])

xp = []
yp = []

n, m = x_train.shape

for i in range(n):
  xp.append(x_train[i])  
  if (y_train[i][0] == 1):
    yp.append(1)
  else:
    yp.append(0)

xp = np.array(xp)
yp = np.array(yp)

costs1, grads1, w1 = model(w, xp, yp, iterations, alpha)

In [ ]:
costs1[-1]

array([1.43911007])

In [ ]:
alpha = 0.1
iterations = 10000
w = np.random.randn(1, x_train.shape[1])


# model 2
# 2 is positive, 1 and 3 are negative
xp = []
yp = []

n, m = x_train.shape

for i in range(n):
  xp.append(x_train[i])  
  if (y_train[i][0] == 2):
    yp.append(1)
  else:
    yp.append(0)

xp = np.array(xp)
yp = np.array(yp)

costs2, grads2, w2 = model(w, xp, yp, iterations, alpha)

In [ ]:
costs2[-1]

array([1.63098141])

In [ ]:
alpha = 0.01
iterations = 10000
w = np.random.randn(1, x_train.shape[1])

In [ ]:
# model 3
# 3 is positive, 1 and 2 are negative
xp = []
yp = []

n, m = x_train.shape

for i in range(n):
  xp.append(x_train[i])  
  if (y_train[i][0] == 3):
    yp.append(1)
  else:
    yp.append(0)

xp = np.array(xp)
yp = np.array(yp)

costs3, grads3, w3 = model(w, xp, yp, iterations, alpha)

In [ ]:
costs3[-1]

array([0.53512523])

In [ ]:
pred1 = sigmoid(np.dot(w1, x_test.T))[0]

# for model1
n, m = x_test.shape

tp = 0
fp = 0
tn = 0
fn = 0
classnum = 1


for i in range(n):
  if (pred1[i] >= 0.5):
    pred1[i] = 0.0
  else:
    pred1[i] = 1.0


for i in range(n):
  if (y_test[i] == classnum):
    if (pred1[i] == classnum):
      tp += 1
    else:
      fn += 1

  else:
    if (pred1[i] == classnum):
      fp += 1
    else:
      tn += 1

# accuracy
acc = (tp + tn) / (tp + tn + fp + fn)

# sensitivity
sen = tp / (tp + fn)

# specificity
spec = tn / (tn + fp)

print("For Model 1:")
print("Accuracy = " + str(acc))
print("Sensitivity = " + str(sen))
print("Specificity = " + str(spec))

For Model 1:
Accuracy = 0.6666666666666666
Sensitivity = 0.0
Specificity = 1.0


In [ ]:
pred2 = sigmoid(np.dot(w2, x_test.T))[0]

# for model2
n, m = x_test.shape

tp = 0
fp = 0
tn = 0
fn = 0
classnum = 2


for i in range(n):
  if (pred2[i] >= 0.5):
    pred2[i] = 0.0
  else:
    pred2[i] = 1.0


for i in range(n):
  if (y_test[i] == classnum):
    if (pred2[i] == classnum):
      tp += 1
    else:
      fn += 1

  else:
    if (pred2[i] == classnum):
      fp += 1
    else:
      tn += 1

# accuracy
acc = (tp + tn) / (tp + tn + fp + fn)

# sensitivity
sen = tp / (tp + fn)

# specificity
spec = tn / (tn + fp)

print("For Model 2:")
print("Accuracy = " + str(acc))
print("Sensitivity = " + str(sen))
print("Specificity = " + str(spec))

For Model 2:
Accuracy = 0.7
Sensitivity = 0.0
Specificity = 1.0


In [ ]:
pred3 = sigmoid(np.dot(w3, x_test.T))[0]

# for model3
n, m = x_test.shape

tp = 0
fp = 0
tn = 0
fn = 0
classnum = 3


for i in range(n):
  if (pred3[i] >= 0.5):
    pred3[i] = 0.0
  else:
    pred3[i] = 1.0


for i in range(n):
  if (y_test[i] == classnum):
    if (pred3[i] == classnum):
      tp += 1
    else:
      fn += 1

  else:
    if (pred3[i] == classnum):
      fp += 1
    else:
      tn += 1

# accuracy
acc = (tp + tn) / (tp + tn + fp + fn)

# sensitivity
sen = tp / (tp + fn)

# specificity
spec = tn / (tn + fp)

print("For Model 3:")
print("Accuracy = " + str(acc))
print("Sensitivity = " + str(sen))
print("Specificity = " + str(spec))

For Model 3:
Accuracy = 0.6333333333333333
Sensitivity = 0.0
Specificity = 1.0
